/* Titre : tennisStructure.sql*/
/* Auteur : raphael.favre@cpnv.ch*/
/* Version : 28-SEP-2019*/

-- MySQL Script generated by MySQL Workbench
-- Sat Sep 28 06:56:31 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema Tennis
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `Tennis` ;

-- -----------------------------------------------------
-- Schema Tennis
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Tennis` DEFAULT CHARACTER SET utf8 ;
USE `Tennis` ;

-- -----------------------------------------------------
-- Table `Tennis`.`sponsors`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Tennis`.`sponsors` ;

CREATE TABLE IF NOT EXISTS `Tennis`.`sponsors` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Tennis`.`players`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Tennis`.`players` ;

CREATE TABLE IF NOT EXISTS `Tennis`.`players` (
  `id` INT NOT NULL,
  `firstName` VARCHAR(100) NULL,
  `lastName` VARCHAR(100) NULL,
  `sponsor_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_players_sponsors_idx` (`sponsor_id` ASC),
  CONSTRAINT `fk_players_sponsors`
    FOREIGN KEY (`sponsor_id`)
    REFERENCES `Tennis`.`sponsors` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
